wandb_version: 1

bid:
  desc: null
  value: true
cell_type:
  desc: null
  value: RNN
dropout:
  desc: null
  value: 1
embedding_size:
  desc: null
  value: 64
epoch:
  desc: null
  value: 50
hidden_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.001
num_layer:
  desc: null
  value: 3
method:
  desc: null
  value: grid
name:
  desc: null
  value: Loss
metric:
  desc: null
  value:
    goal: maximize
    name: validation_accuracy
parameters:
  desc: null
  value:
    hidden_size:
      values:
      - 128
      - 256
    num_layer:
      values:
      - 1
      - 2
      - 3
      - 4
      - 5
    embedding_size:
      values:
      - 64
      - 128
      - 256
    cell_type:
      values:
      - RNN
      - GRU
      - LSTM
    bid:
      values:
      - true
      - false
    dropout:
      values:
      - 1
    epoch:
      values:
      - 50
      - 40
    lr:
      values:
      - 0.001
      - 0.01
      - 0.001
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684097895.976084
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.8.10
      5: 0.14.2
      8:
      - 5
