wandb_version: 1

bid:
  desc: null
  value: false
cell_type:
  desc: null
  value: LSTM
dropout:
  desc: null
  value: 0
embedding_size:
  desc: null
  value: 300
epoch:
  desc: null
  value: 20
hidden_size:
  desc: null
  value: 512
lr:
  desc: null
  value: 0.001
num_layer:
  desc: null
  value: 3
method:
  desc: null
  value: random
name:
  desc: null
  value: Loss
metric:
  desc: null
  value:
    goal: maximize
    name: validation_accuracy
parameters:
  desc: null
  value:
    hidden_size:
      values:
      - 512
    num_layer:
      values:
      - 3
    embedding_size:
      values:
      - 300
    cell_type:
      values:
      - LSTM
    bid:
      values:
      - false
    dropout:
      values:
      - 0
    epoch:
      values:
      - 20
    lr:
      values:
      - 0.001
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684497690.79174
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.10
      5: 0.15.0
      8:
      - 5
