wandb_version: 1

bid:
  value: false
cell_type:
  value: LSTM
dropout:
  value: 0.5
embedding_size:
  value: 300
epoch:
  value: 20
hidden_size:
  value: 128
lr:
  value: 0.001
num_layer:
  value: 3
